---
title: "Assignments"
output:
  html_document:
    toc: yes
    toc_float: yes
    collapsed: no
    number_sections: no
    toc_depth: 1
  pdf_document:
    toc: no
    toc_depth: '1'
---


This page will contain code worked on in class.

09/22/21 Breakout Room Activity

These are the steps I took to load the data: 



***Variables***: mjage, cigever, alcever, AGE2, sexatract, speakengl, irsex. 
***What types of variables are they?*** Categorical variables 


** How big is the dataset?*** - I got two numbers 426 and 7, is 426 how many individual are in the data, and 7 the number of categories? 


Make a histogram of age2.
```{r}
hist(dat$AGE2, main="Histogram of age", xlab="Code for age", ylab="Frequency")
```

**What do the #s represent?** The numbers/bins on the x-axis represent the code associated with the age of respondents. For example, 5 doesn't mean that the respondent is 5 years old - when we look at the age associated with that code in the codebook we would see that the respondent is 16 years old. Same for 15 on the x-axis, the codebook tells us that the respondennt is between 35-49 years old. The numbers on the y-axis represent the frequency of indviduals that fit into each of those groups. 






$$\\[2in]$$







# Assignment 2 

(Coming soon)


