<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Assignments</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Carolina H's Site</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Journal.html">Assignments</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Assignments</h1>

</div>


<p>This page will contain all the assignments you submit for the class.</p>
<div id="assignment-1" class="section level1">
<h1>Assignment 1</h1>
<p><strong>Collaborators: Eliza Epstein. </strong></p>
<p>This assignment is due on Canvas on Monday 9/20 before class, at 10:15 am. Include the name of anyone with whom you collaborated at the top of the assignment.</p>
<div id="problem-1" class="section level3">
<h3>Problem 1</h3>
<p>Install the datasets package on the console below using <code>install.packages("datasets")</code>. Now load the library.</p>
<pre class="r"><code>library(datasets)</code></pre>
<p><strong>Answer</strong>: I loaded the library!</p>
<p>Load the USArrests dataset and rename it <code>dat</code>. Note that this dataset comes with R, in the package datasets, so there’s no need to load data from your computer. Why is it useful to rename the dataset?</p>
<pre class="r"><code>dat&lt;-USArrests</code></pre>
<p><strong>Answer</strong>: It is nice to rename data because we want to be able to replicate our analysis without messing up the original data.</p>
</div>
<div id="problem-2" class="section level3">
<h3>Problem 2</h3>
<p>Use this command to make the state names into a new variable called State.</p>
<pre class="r"><code>dat$state &lt;- tolower(rownames(USArrests))</code></pre>
<p>List the variables contained in the dataset <code>USArrests</code>.</p>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>## [1] &quot;Murder&quot;   &quot;Assault&quot;  &quot;UrbanPop&quot; &quot;Rape&quot;</code></pre>
<p><strong>Answer</strong>: The four variables contained in this dataset are Murder, Assault, UrbanPop and Rape.</p>
</div>
<div id="problem-3" class="section level3">
<h3>Problem 3</h3>
<p>What type of variable (from the DVB chapter) is <code>Murder</code>?</p>
<p><strong>Answer</strong>: Murder is a categorical variable, according to the DVB chapter. — FALSE: It’s a quantitative variable.</p>
<p>What R Type of variable is it?</p>
<p><strong>Answer</strong>: It is a character R Type variable. — FALSE: It’s a numeriical varable.</p>
</div>
<div id="problem-4" class="section level3">
<h3>Problem 4</h3>
<p>What information is contained in this dataset, in general? What do the numbers mean?</p>
<p><strong>Answer</strong>: In this dataset we have the number of arrests per 100,000 residents for each of the following categories: assault, murder and rape in each of the 50 US states in 1973.</p>
</div>
<div id="problem-5" class="section level3">
<h3>Problem 5</h3>
<p>Draw a histogram of <code>Murder</code> with proper labels and title.</p>
<p><strong>Answer</strong>: I chose to make a barplot instead of a histogram because it made more sense to me, considering that the data is categorical. I thought it would be clearer if each bar represented a state, which is why I decided to label the x-axis with the names of the states and the y-axis the number of arrests for murder per 100,000. In the code las=2 simply means that I wanted that state labels to be perpendicular to the x-axis.</p>
<pre class="r"><code>state.names = row.names(USArrests)
barplot(USArrests$Murder, names.arg = state.names, las = 2, ylab = &quot;Arrest Rate for murder per 100,000&quot;, main = &quot;Murder Rate in the United States in 1973&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="problem-6" class="section level3">
<h3>Problem 6</h3>
<p>Please summarize <code>Murder</code> quantitatively. What are its mean and median? What is the difference between mean and median? What is a quartile, and why do you think R gives you the 1st Qu. and 3rd Qu.?</p>
<pre class="r"><code>summary(dat$Murder)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.800   4.075   7.250   7.788  11.250  17.400</code></pre>
<p><strong>Answer</strong>: Min: 0.800, 1st Q: 4.075, Median 7.250, Mean 7.788, 3rd Q 11.250, Max 17.400 —– The mean is 7.788 and the median is 7.250. On average there were 7.788 (mean) arrests for murder per 100,000 residents in each state in 1973. The median tells us where the middle of the data set is. Since the mean is higher than the median we could say the distribution or arrests for murder per 100,000 in 1973 is positively skewed. A quartile represents 1/4 of the data, for examples the 1st Q is 4.075 and this tells us that 1/4 of the data lies below 4.075 arrests per 100,000. I think R only gives us the 1st and 3rd Quartiles because the median is equal to the 2nd Quartile.</p>
</div>
<div id="problem-7" class="section level3">
<h3>Problem 7</h3>
<p>Repeat the same steps you followed for <code>Murder</code>, for the variables <code>Assault</code> and <code>Rape</code>. Now plot all three histograms together. You can do this by using the command <code>par(mfrow=c(3,1))</code> and then plotting each of the three.</p>
<pre class="r"><code>state.names = row.names(USArrests)
barplot(USArrests$Assault, names.arg = state.names, las = 2, ylab = &quot;Arrest Rate for assault per 100,000&quot;, main = &quot;Assault Rate in the United States in 1973&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>state.names = row.names(USArrests)
barplot(USArrests$Rape, names.arg = state.names, las = 2, ylab = &quot;Arrest Rate for rape per 100,000&quot;, main = &quot;Rape Rate in the United States in 1973&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(3,1))
state.names = row.names(USArrests)
barplot(USArrests$Murder, names.arg = state.names, las = 2, ylab = &quot;Arrest Rate for murder per 100,000&quot;, main = &quot;Murder Rate in the United States in 1973&quot;)

state.names = row.names(USArrests)
barplot(USArrests$Assault, names.arg = state.names, las = 2, ylab = &quot;Arrest Rate for assault per 100,000&quot;, main = &quot;Assault Rate in the United States in 1973&quot;)

state.names = row.names(USArrests)
barplot(USArrests$Rape, names.arg = state.names, las = 2, ylab = &quot;Arrest Rate for rape per 100,000&quot;, main = &quot;Rape Rate in the United States in 1973&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>What does the command par do, in your own words (you can look this up by asking R <code>?par</code>)?</p>
<p><strong>Answer</strong>: Par can be used to set different parameters and can allow us to create a single graph from many.</p>
<p>What can you learn from plotting the histograms together?</p>
<p><strong>Answer</strong>: By plotting histograms together (or in this case bar charts) we can see patterns more clearly. It becomes easier to compare the rates of arrest per 100,000 residents for each category across the states.</p>
</div>
<div id="problem-8" class="section level3">
<h3>Problem 8</h3>
<p>In the console below (not in text), type <code>install.packages("maps")</code> and press Enter, and then type <code>install.packages("ggplot2")</code> and press Enter. This will install the packages so you can load the libraries.</p>
<p>Run this code:</p>
<pre class="r"><code>library(&#39;maps&#39;) 
library(&#39;ggplot2&#39;) 

ggplot(dat, aes(map_id=state, fill=Murder)) + 
  geom_map(map=map_data(&quot;state&quot;)) + 
  expand_limits(x=map_data(&quot;state&quot;)$long, y=map_data(&quot;state&quot;)$lat)</code></pre>
<p>What does this code do? Explain what each line is doing.</p>
<p><strong>Answer</strong>:The code allows us to make a heat map of arrests for murder per 100,000 in the USA. The first line tells R that we want to make a heat map according to states and that we want to use the data of arrests for murder to fill in each state. The second line creates the map and the last line expands the range to fit in all possible values.</p>
<p><span class="math display">\[\\[2in]\]</span></p>
</div>
</div>
<div id="assignment-2" class="section level1">
<h1>Assignment 2</h1>
<p>#Carolina Herrera Figueroa # CRIM250- Statistics for the Social Sciences # Assignment 2 # Collaborators: Eliza Epstein</p>
<p>##“/Users/carolinaherrera/Documents/Assignment 2 - CRIM 250”</p>
<pre class="r"><code>dat&lt;-read.csv(&quot;dat.nsduh.small.1.csv&quot;)</code></pre>
<pre class="r"><code>summary(dat)</code></pre>
<pre><code>##      mjage           cigage         iralcage          age2      
##  Min.   : 7.00   Min.   :10.00   Min.   : 5.00   Min.   : 4.00  
##  1st Qu.:14.00   1st Qu.:15.00   1st Qu.:13.00   1st Qu.:13.00  
##  Median :16.00   Median :17.00   Median :15.00   Median :15.00  
##  Mean   :15.99   Mean   :17.65   Mean   :14.95   Mean   :13.98  
##  3rd Qu.:17.50   3rd Qu.:19.00   3rd Qu.:17.00   3rd Qu.:15.00  
##  Max.   :35.00   Max.   :50.00   Max.   :23.00   Max.   :17.00  
##    sexatract       speakengl        irsex      
##  Min.   : 1.00   Min.   :1.00   Min.   :1.000  
##  1st Qu.: 1.00   1st Qu.:1.00   1st Qu.:1.000  
##  Median : 1.00   Median :1.00   Median :1.000  
##  Mean   : 3.07   Mean   :1.07   Mean   :1.468  
##  3rd Qu.: 1.00   3rd Qu.:1.00   3rd Qu.:2.000  
##  Max.   :99.00   Max.   :3.00   Max.   :2.000</code></pre>
<pre class="r"><code>head(dat)</code></pre>
<pre><code>##   mjage cigage iralcage age2 sexatract speakengl irsex
## 1    14     50       14   16         1         1     1
## 2    11     14        5   13         2         1     2
## 3    12     35       12   15         2         1     2
## 4    16     18       18   14         1         1     1
## 5    14     16       14   16         4         1     1
## 6    12     16       18   15         4         1     2</code></pre>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>## [1] &quot;mjage&quot;     &quot;cigage&quot;    &quot;iralcage&quot;  &quot;age2&quot;      &quot;sexatract&quot; &quot;speakengl&quot;
## [7] &quot;irsex&quot;</code></pre>
<pre class="r"><code>dim(dat)</code></pre>
<pre><code>## [1] 171   7</code></pre>
<p><strong>Answer</strong>:The data consists of 171 rows and 7 columns.</p>
<p>#Problem 2: Variables <strong>ANSWER</strong>: The variables in this data set are: mjage, cigage, iralcage, age2, sexatract, speakengl, irsex. (mjage) looks at how old the individual was the first time they used marijuana or hashish, (cigage) is have they ever smoked part of a cigarette, (iralcage) looks at how old the individual was when they first tried alcohol, (age2) represents their coded age, (irsex) represents their gender, (sexatract) looks at what best describes their sexual atractment and (speakengl) represents how well the individual speaks English. These are all categorical variables.</p>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>## [1] &quot;mjage&quot;     &quot;cigage&quot;    &quot;iralcage&quot;  &quot;age2&quot;      &quot;sexatract&quot; &quot;speakengl&quot;
## [7] &quot;irsex&quot;</code></pre>
<p>What is this dataset about? Who collected the data, what kind of sample is it, and what was the purpose of generating the data? <strong>Answer</strong>: This dataset is about drug and alcohol use. It was collected using the National Survey of Drug Use and Health, and this is a random sample of the first 1000 cases of the survey. The purpose of generating the data was to perhaps be able to study the relationship between drug use and other variables such as age or gender. I think the results could perhaps be used to allocate resources to individuals or groups at highest risk of an early onset of drug use.</p>
<hr />
<p>#Problem 3: Age and gender What is the age distribution of the sample like? Make sure you read the codebook to know what the variable values mean. <strong>Answer</strong>: The age distribution of the sample is skewed with most individuals being between the ages of 35-49 years old, where the peak and the mean of the data is located, as shown by Figure 1. The lowest age of a respondent was 15 years old. I think those over 65 years old are also underrepresented in the sample.</p>
<pre class="r"><code>summary(dat)</code></pre>
<pre><code>##      mjage           cigage         iralcage          age2      
##  Min.   : 7.00   Min.   :10.00   Min.   : 5.00   Min.   : 4.00  
##  1st Qu.:14.00   1st Qu.:15.00   1st Qu.:13.00   1st Qu.:13.00  
##  Median :16.00   Median :17.00   Median :15.00   Median :15.00  
##  Mean   :15.99   Mean   :17.65   Mean   :14.95   Mean   :13.98  
##  3rd Qu.:17.50   3rd Qu.:19.00   3rd Qu.:17.00   3rd Qu.:15.00  
##  Max.   :35.00   Max.   :50.00   Max.   :23.00   Max.   :17.00  
##    sexatract       speakengl        irsex      
##  Min.   : 1.00   Min.   :1.00   Min.   :1.000  
##  1st Qu.: 1.00   1st Qu.:1.00   1st Qu.:1.000  
##  Median : 1.00   Median :1.00   Median :1.000  
##  Mean   : 3.07   Mean   :1.07   Mean   :1.468  
##  3rd Qu.: 1.00   3rd Qu.:1.00   3rd Qu.:2.000  
##  Max.   :99.00   Max.   :3.00   Max.   :2.000</code></pre>
<pre class="r"><code>counts &lt;- table(dat$age2)
barplot(counts, main = &quot;Fig 1. Age of Participants&quot;, xlab=&quot;Code for Age&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Do you think this age distribution representative of the US population? Why or why not? ANSWER: I think this age distribution is not representative of the US population because it suggests that the population is mostly comprised of individuals between the age of 35-49 years old.</p>
<p>Is the sample balanced in terms of gender? If not, are there more females or males? <strong>ANSWER</strong>: The same seems to be relatively balanced in terms of gender, but there are slightly more males than females. The bar chart (Figure 2) shows us that the bar for code “1” which represents males in the codebook is taller, meaning our sample has more males.</p>
<pre class="r"><code>counts &lt;- table(dat$irsex)
barplot(counts, main = &quot;Fig 2. Gender of Participants&quot;, xlab=&quot;Code for Gender&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Use this code to draw a stacked bar plot to view the relationship between sex and age. What can you conclude from this plot? <strong>ANSWER</strong>: This plot shows us that for most age categories an equal number of males and females were surveyed, with the exception of a few. It seems that the younger the participants were the more likely it was that the sample consisted of mostly males or mostly females, but it was not even. For example, for age categories 6 and 7, which translates to the respondents being 17 or 18 years old, the data is made up of males only. Starting at age category 11 we see a sample more evenly split among males and females.</p>
<pre class="r"><code>tab.agesex &lt;- table(dat$irsex, dat$age2)
barplot(tab.agesex,
        main = &quot;Fig 3. Relationship between Sex and Age&quot;,
        xlab = &quot;Age category&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.agesex),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div id="problem-4-substance-use" class="section level2">
<h2>Problem 4: Substance use</h2>
<p>For which of the three substances included in the dataset (marijuana, alcohol, and cigarettes) do individuals tend to use the substance earlier? <strong>Answer</strong>: Individuals tends to use alcohol earlier, it was reported being consumed as early as 16 years old, compared with 18 years old for marijuana/hashnish and 21 years old for cigarettes. We can also see that 25% of the respondents were under the age of 29 when they tried alcohol for the first time, compared to 25% being below 34 years old the first time they tried marijuana/hashish and 25% of those who respondents who were under 49 years old when theey started smoking cigarettes. Alcohol is also the only substance in our sample that respondents tried for the first time under the age of 18.</p>
<pre class="r"><code>counts &lt;- table(dat$mjage)
barplot(counts, main = &quot;Fig 4. Age when First Used Marijuana/Hashish&quot;, xlab=&quot;Age&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre class="r"><code>counts &lt;- table(dat$cigage)
barplot(counts, main = &quot;Fig 5. Age when first started Smoking Cigarettes Every day&quot;, xlab=&quot;Age&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code>counts &lt;- table(dat$iralcage)
barplot(counts, main = &quot;Fig 6. Age When First tried Alcohol&quot;, xlab=&quot;Age&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<hr />
</div>
<div id="problem-5-sexual-attraction" class="section level2">
<h2>Problem 5: Sexual attraction</h2>
<p>What does the distribution of sexual attraction look like? Is this what you expected? <strong>ANSWER</strong>: The distribution of sexual attraction is skewed, with a great majority of individuals reporting as being attracted only to the opposite sex. I was not surprised to see such a high number of individuals reporting to be heterosexual, but rather the difference between those who reported to be heterosexual and those who reported to be homosexual. I think we should keep in mind that it’s possible that some individuals may have chosen to not report accurately out of fear of embarassment.</p>
<pre class="r"><code>counts &lt;- table(dat$sexatract)
barplot(counts, main = &quot; Fig 7:Sexual Attraction&quot;, xlab=&quot;Code for Sexual Attraction&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>What is the distribution of sexual attraction by gender? <strong>Answer</strong>: The distribution of sexual attraction by gender is interesting because those who identify as strongly being heterosexual (1 on the codebook) are mostly males, while those who identify as being “mostly heterosexual” are mostly female. I thought this was interesting to see because it may be showing us the importance of the wording of the question since males were more likley to choose the option that strongly asserted their sexuality. In our sample of 1,000 individuals, those who identified as bisexual were only female. There was an even split between genders among those who identified as being attracted only to the same sex.</p>
<pre class="r"><code>tab.sexatract &lt;- table(dat$irsex, dat$sexatract)
barplot(tab.sexatract,
        main = &quot;Fig 8: Relationship between Gender and Sexual Attraction&quot;,
        xlab = &quot;Code for Sexual Attraction&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.sexatract),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
<div id="problem-6-english-speaking" class="section level2">
<h2>Problem 6: English speaking</h2>
<p>What does the distribution of English speaking look like in the sample? Is this what you might expect for a random sample of the US population? <strong>ANSWER</strong>: The distribution of English speaking looks very skewed in the sample, with the majority of individuals speaking English very well. The barplot shows us that over 150 individuals speak English very well while about 10 speak English not well. This is not what I would expect of a random sample of the US population, I expected to see a greater number of individuals who spoke English “well” and “not well” considering that English is not the nativie language for a great portion of the population. I didn’t expect the data to be as skewed at it is.</p>
<p>Are there more English speaker females or males? <strong>ANSWER</strong>: There are more English speaking males, and in our sample none fall under the category of speaking English “not well”, represented by the bar labeled “3” on our plot.</p>
<pre class="r"><code>counts &lt;- table(dat$speakengl)
barplot(counts, main = &quot;Figure 9: How Well do Participants Speak English&quot;, xlab = &quot;Categories&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre class="r"><code>tab.sexengl &lt;- table(dat$irsex, dat$speakengl)
barplot(tab.sexengl,
        main = &quot;Figure 10: English Proficiency by Gender&quot;,
        xlab = &quot;Code for English Speaking&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.sexengl),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
</div>
</div>
<div id="exam-1" class="section level1">
<h1>Exam 1</h1>
<pre class="r"><code>dat&lt;-read.csv(&quot;fatal-police-shootings-data.csv&quot;)</code></pre>
<div id="problem-1-10-points" class="section level2">
<h2>Problem 1 (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>Describe the dataset. This is the source: <a href="https://github.com/washingtonpost/data-police-shootings" class="uri">https://github.com/washingtonpost/data-police-shootings</a> . Write two sentences (max.) about this.</li>
</ol>
<p><strong>This dataset describes every fatal shooting in the United States since January 1, 2015 by a police officer on the line of duty. It tracks different variables about the circumstances of the shooting including if the victim was armed or not.</strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>How many observations are there in the data frame?</li>
</ol>
<pre class="r"><code>dim(dat)</code></pre>
<pre><code>## [1] 6594   17</code></pre>
<p><strong>The data consists of 6594 rows and 17 columns..</strong></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Look at the names of the variables in the data frame. Describe what “body_camera”, “flee”, and “armed” represent, according to the codebook. Again, only write one sentence (max) per variable.</li>
</ol>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>##  [1] &quot;id&quot;                      &quot;name&quot;                   
##  [3] &quot;date&quot;                    &quot;manner_of_death&quot;        
##  [5] &quot;armed&quot;                   &quot;age&quot;                    
##  [7] &quot;gender&quot;                  &quot;race&quot;                   
##  [9] &quot;city&quot;                    &quot;state&quot;                  
## [11] &quot;signs_of_mental_illness&quot; &quot;threat_level&quot;           
## [13] &quot;flee&quot;                    &quot;body_camera&quot;            
## [15] &quot;longitude&quot;               &quot;latitude&quot;               
## [17] &quot;is_geocoding_exact&quot;</code></pre>
<p><strong>The variable “body_camera” looks at whether news reports indicate that a officer was wearing a body camera and if it possibly recorded some part of the incident.“flee” looks at whether news reports indicate that the victim was moving away from the officers and there are three possible responses: “by foot”, “car” or “not fleeing”. “Armed” looks at whether the victim was armed with some sort of artifact that a police officer believed could inflict harm, the possible responses are that this is “undetermined”, “unknown” or the victim was “unarmed”.</strong></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What are three weapons that you are surprised to find in the “armed” variable? Make a table of the values in “armed” to see the options.</li>
</ol>
<pre class="r"><code>table(dat$armed)</code></pre>
<pre><code>## 
##                                                   air conditioner 
##                              207                                1 
##                       air pistol                   Airsoft pistol 
##                                1                                3 
##                               ax                         barstool 
##                               24                                1 
##                     baseball bat          baseball bat and bottle 
##                               20                                1 
## baseball bat and fireplace poker           baseball bat and knife 
##                                1                                1 
##                            baton                           BB gun 
##                                6                               15 
##               BB gun and vehicle                     bean-bag gun 
##                                1                                1 
##                      beer bottle                       binoculars 
##                                3                                1 
##                     blunt object                           bottle 
##                                5                                1 
##                    bow and arrow                       box cutter 
##                                1                               13 
##                            brick              car, knife and mace 
##                                2                                1 
##                          carjack                            chain 
##                                1                                3 
##                        chain saw                         chainsaw 
##                                2                                1 
##                            chair              claimed to be armed 
##                                4                                1 
##               contractor&#39;s level                   cordless drill 
##                                1                                1 
##                         crossbow                          crowbar 
##                                9                                5 
##                        fireworks                         flagpole 
##                                1                                1 
##                       flashlight                      garden tool 
##                                2                                2 
##                      glass shard                          grenade 
##                                4                                1 
##                              gun                      gun and car 
##                             3798                               12 
##                    gun and knife                  gun and machete 
##                               22                                3 
##                    gun and sword                  gun and vehicle 
##                                1                               17 
##              guns and explosives                           hammer 
##                                3                               18 
##                       hand torch                          hatchet 
##                                1                               14 
##                  hatchet and gun                         ice pick 
##                                2                                1 
##                incendiary device                            knife 
##                                2                              955 
##                knife and vehicle                 lawn mower blade 
##                                1                                2 
##                          machete                  machete and gun 
##                               51                                1 
##                     meat cleaver                  metal hand tool 
##                                6                                2 
##                     metal object                       metal pipe 
##                                5                               16 
##                       metal pole                       metal rake 
##                                4                                1 
##                      metal stick                       microphone 
##                                3                                1 
##                       motorcycle                         nail gun 
##                                1                                1 
##                              oar                       pellet gun 
##                                1                                3 
##                              pen                     pepper spray 
##                                1                                2 
##                         pick-axe                    piece of wood 
##                                4                                7 
##                             pipe                        pitchfork 
##                                7                                2 
##                             pole                   pole and knife 
##                                3                                2 
##                  railroad spikes                             rock 
##                                1                                7 
##                    samurai sword                         scissors 
##                                4                                9 
##                      screwdriver                     sharp object 
##                               16                               14 
##                           shovel                            spear 
##                                7                                2 
##                          stapler              straight edge razor 
##                                1                                5 
##                            sword                            Taser 
##                               23                               34 
##                        tire iron                       toy weapon 
##                                4                              226 
##                          unarmed                     undetermined 
##                              421                              188 
##                   unknown weapon                          vehicle 
##                               82                              213 
##                  vehicle and gun              vehicle and machete 
##                                8                                1 
##                    walking stick                       wasp spray 
##                                1                                1 
##                           wrench 
##                                1</code></pre>
<p><strong>Three weapons that surprised me in the “armed” variable are pen, wasp spray, and chainsaw.</strong></p>
</div>
<div id="problem-2-10-points" class="section level2">
<h2>Problem 2 (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>Describe the age distribution of the sample. Is this what you would expect to see?</li>
</ol>
<pre class="r"><code>hist(dat$age, main=&quot;Fig 1. Histogram of age of Victims&quot;, xlab=&quot;Years&quot;, ylab=&quot;Frequency&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p><strong>The age distribution of the sample is what is would have expected to see. Looking at figure 1 we can see that a great portion of the victims are between the age of 30-35. Usually people between this age are more likely to be involved in interactions with the police. For example, I wasn’t expecting a large number of victims to be either under the age of 20, nor over the age of 45 and the histogram shows that to be true. The distribution is also unimodal and positvely skewed to the right. </strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>To understand the center of the age distribution, would you use a mean or a median, and why? Find the one you picked.</li>
</ol>
<pre class="r"><code>summary(dat$age)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    6.00   27.00   35.00   37.12   45.00   91.00     308</code></pre>
<p><strong>To understand the center of the age distribution I would use a median because it is resistant to values that are extremely large or small. Since the data is skewed to the right our mean would also be pulled to the right, giving us a number that does not represent the true center of the distribution. The median of the age distribution is 35 years old, meaning that the center of our data is located here. </strong></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Describe the gender distribution of the sample. Do you find this surprising?</li>
</ol>
<pre class="r"><code>counts &lt;- table(dat$gender)
barplot(counts, main = &quot;Fig 2. Gender of Victim&quot;, xlab=&quot;Sex&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p><strong>Figure 2 shows us that most of the victims were male, with a very small number identifying as female. I don’t find this surprising because usually when we hear about fatal police shootings the victims are always male. This could be either because they are more likley to put up a fight and resist to an arrest or because they are more likely to be stopped in the first place. The first very small bar in our chart signifies that the gender of the victim is unknown.</strong></p>
</div>
<div id="problem-3-10-points" class="section level2">
<h2>Problem 3 (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>How many police officers had a body camera, according to news reports? What proportion is this of all the incidents in the data? Are you surprised that it is so high or low?</li>
</ol>
<pre class="r"><code>table(dat$body_camera)</code></pre>
<pre><code>## 
## False  True 
##  5684   910</code></pre>
<p><strong>According to news reports 910 police officers had a body camera. 910/6594 – Only in 13.8% of all incidents in the data police officers has a body camera. I found this to actually be very surprising considering the number of states that are requiring their officers to wear body cameras. I think it possible that a portion of these deadly shootings could have been prevented if more officers were required to wear these cameras, because they create a sense of responsibility. There is no way to lie about the circumstances of a deadly shooting if there is videographic evidence of what occurred. </strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>In how many of the incidents was the victim fleeing? What proportion is this of the total number of incidents in the data? Is this what you would expect?</li>
</ol>
<pre class="r"><code>table(dat$flee)</code></pre>
<pre><code>## 
##                     Car        Foot Not fleeing       Other 
##         491        1058         845        3952         248</code></pre>
<p><strong>The victim was fleeing in 1903 of the incidents, 1058 by car and 845 by foot. There are 491 missing values in this dataset, if we include those in the calculation, the victim was fleeing in 1903/6594 – 28.85% of the cases. If we do not include the missing values, the victim was fleeing in 31.18% of cases. This is not what I expected because it shows that the police officer did not have much reason to shoot the victim in a fatal way. If the individual isn’t fleeing then they are most likely not a source of imminent danger to the public, meaning there must be another way to get control over them. I would have expected the proportion of victims fleeing to be at least 50%.</strong></p>
</div>
<div id="problem-4-10-points---answer-only-one-of-these-a-or-b." class="section level2">
<h2>Problem 4 (10 points) - Answer only one of these (a or b).</h2>
<ol style="list-style-type: lower-alpha">
<li>Describe the relationship between the variables “body camera” and “flee” using a stacked barplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the options for “flee”, each bar contains information about whether the police officer had a body camera (vertically), and the height along the y-axis shows the frequency of that category).</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for barplot, run ?barplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<pre class="r"><code>tab.agesex &lt;- table(dat$body_camera, dat$flee)
barplot(tab.agesex,
        main = &quot;Fig 3. Relationship between Body Camera and Flee&quot;,
        xlab = &quot;Victim fleeing&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.agesex),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p><strong>Figure 3 first shows us that most of the victims were not fleeing. Secondly, it shows us that more police officers were wearing cameras when the victim was not fleeing compared to when they were. I wouldn’t exactly say that there is an association between the two considering that police officers probably cannot take off their body cameras in the middle of their shift simply because it is convenient for the situation. I do think it’s off to see how in how many of these fatal shootings there is actual video evidence of what happened. The first bar in our plot is unlabeled in the dataset, so we are unsure of what that represents. There is also an “other” category where we see a small percentage of body cameras being used. I think this leaves a lot to think about because we don’t know if people in this category were fleeing or if there actions were open to ambiguity. This sort of makes me question the rest of the data and why some things aren’t specifically described or how were circumstances categorized. But overall, we can conclude that in our data more police officers were wearing body cameras that may have recoded part of the incident when the victim was not fleeing compared to when they were fleeing.</strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Describe the relationship between age and race by using a boxplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the race categories and the height along the y-axis is age.</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for boxplot, run ?boxplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<p><strong>Your answer here.</strong></p>
</div>
<div id="extra-credit-10-points" class="section level2">
<h2>Extra credit (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>What does this code tell us?</li>
</ol>
<pre class="r"><code>mydates &lt;- as.Date(dat$date)
head(mydates)
(mydates[length(mydates)] - mydates[1])</code></pre>
<p><strong>This code tells us the number of days that have passed since the first data point was collected. 2458 days have passed since January 1, 2015.</strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>On Friday, a new report was published that was described as follows by The Guardian: “More than half of US police killings are mislabelled or not reported, study finds.” Without reading this article now (due to limited time), why do you think police killings might be mislabelled or underreported? <strong>I think some police killings might not be reported because it is unconvenient for the officer and the city. Perhaps it can affect their budget and how they are viewed by the public. The lack of body cameras also makes this more possible since we don’t have video evidence to prove exactly how the situation occurred.</strong></p></li>
<li><p>Regarding missing values in problem 4, do you see any? If so, do you think that’s all that’s missing from the data?</p></li>
</ol>
</div>
</div>
<div id="assignmennt-3-upload" class="section level1">
<h1>Assignmennt 3– UPLOAD</h1>
<p>Due date: Wednesday 10/27/2021 before class.</p>
</div>
<div id="exam-2-upload" class="section level1">
<h1>Exam 2 Upload</h1>
</div>
<div id="assignment-4" class="section level1">
<h1>Assignment 4</h1>
<p>#Carolina Herrera Figueroa #CRIM 250</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>This is to laod the package tidyverse, which is used for data analysis. </code></pre>
<p>We want to answer the question: what does the relationship between engine size and fuel efficiency look like?</p>
<pre class="r"><code>ggplot2::mpg</code></pre>
<pre><code>## # A tibble: 234 × 11
##    manufacturer model      displ  year   cyl trans drv     cty   hwy fl    class
##    &lt;chr&gt;        &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;
##  1 audi         a4           1.8  1999     4 auto… f        18    29 p     comp…
##  2 audi         a4           1.8  1999     4 manu… f        21    29 p     comp…
##  3 audi         a4           2    2008     4 manu… f        20    31 p     comp…
##  4 audi         a4           2    2008     4 auto… f        21    30 p     comp…
##  5 audi         a4           2.8  1999     6 auto… f        16    26 p     comp…
##  6 audi         a4           2.8  1999     6 manu… f        18    26 p     comp…
##  7 audi         a4           3.1  2008     6 auto… f        18    27 p     comp…
##  8 audi         a4 quattro   1.8  1999     4 manu… 4        18    26 p     comp…
##  9 audi         a4 quattro   1.8  1999     4 auto… 4        16    25 p     comp…
## 10 audi         a4 quattro   2    2008     4 manu… 4        20    28 p     comp…
## # … with 224 more rows</code></pre>
<p>The dataframe we are using to answer our question is mpg.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>Running the code above helps us create a plot of the variables (displ) on the x-axis and (hwy) on the y-axis Plot shows a negative relationship between enginne size (displ) and fuel efficiency (hwy)</p>
<p>ggplot(data = mpg) + <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))</p>
<p>DOES NOT WORK – ERROR</p>
<p>ggplot(data = mpg)</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>(geom_point) is used to create scatterplots, (aes) means we want to make an aesthetic, the x and y variables remain the same, but by writing color=class we can map the colors of the points to the class variable to show us the class of each car. ggplot2 automatically assigns a unique color to each unique value (in this case class) of the variable.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>Here we are running the same plot as before, the only difference is that instead of mapping class to the color aesthetic, we are mapping it to the size aesthetic – thus why we see the different sizes in the points.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>Here we are now mapping class to the alpha aesthetic – which controls the transparency of the points.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>This plot instead maps class to the shape aesthetic - giving unique values a unique shape. Important note! only 6 shapes are used at a time, all other groups will be unplotted.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = &quot;blue&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>Here we are setting the colors of all the points to blue, just for a visually appealing plot, not for extra information.Note how the last part of the code is written slightly different, with a closed parentheses after the y-variable.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = &quot;blue&quot;))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>This code would indeed not give us blue points, but instead red points with a label titled “blue” as if the name of the variable was “blue”</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = displ &lt; 5))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>(color=displ &lt;5) causes color to appear on the scatterplot for values under 5, or whatever number we specify instead of 5</p>
<p><strong>TROUBLESHOOTING</strong></p>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) This will not work. The + must be at end of the first line, not at the beginning of the second.</p>
<div id="facets---we-can-split-our-plot-into-facets-which-are-subplots-that-display-each-one-subset-of-the-data" class="section level3">
<h3>Facets - we can split our plot into facets which are subplots that display each one subset of the data</h3>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>facet_wrap() allows us to plot by a single variable. Inside the parentheses we write (“~” followed by a variable name, in our case “class”). The variable should be discrete. (nrow) allows us to change how many rows of plots we want, if we have 6 plots we can do 2 rows each with 3 plots, or 3 rows each with 2 plots.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<p>facet_grid() allows us to facet the plot on the combination of two variables.There must be two variables separated by a (~)</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(.~ cyl)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>Using a period (.) instead of a variable name will not facet among the columns.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>Having the variable first and then the (.) means we will not facet among rows.</p>
<p>Note: when using facet_grid() we should usually put the variable with more unique levels in the column.</p>
<p>Note: Geom is the geometrical object that a plot uses to represent data – can be bar geoms, line geoms, boxplot geoms, point geoms, etc.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>geom_smooth gives us a sort of smooth line that is fitted to the data.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>linetype allows us to set a different type of line for each unique variable that we are plotting. setting (linetype=drv) separates the cars into 3 lines based on their drv value, which describes a car’s drivetrain.</p>
<pre class="r"><code>ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-58-2.png" width="672" /></p>
<pre class="r"><code>ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-58-3.png" width="672" /></p>
<p>Plotting it like above allows ggplot2 to draw a separate object for each unique value of the grouping variable. We get 3 different plots without a legend. I’m not exactly sure why we would use this though</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>Here we are plotting multiple geoms in the same plot, we added the function of geom_point and geom_smooth - meaning that we have both a scatterplot and the smooth line that fits the data.</p>
<pre class="r"><code>ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>This code is equivalent to the one above but it’s very useful because if we want to change the y-axis to display a different variable we’d have to change it into two places, but like this it simplifies the process for us. It reduces the possibility that we will make errors in our code.</p>
<pre class="r"><code>ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>We can display different aesthetic in different layers because ggplot2 treats the place mappings as local mappings for the layer. In this case we are mapping class to the color aesthetic only for the point geom.</p>
<pre class="r"><code>ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == &quot;subcompact&quot;), se = FALSE)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>We can also specify different data for each layer. The smoothline displays just a subset of the mpg dataset, the subcompact car cars. If we wanted to look only at the minivan cars, we would change it to (class == “minivan”) What does se mean?</p>
</div>
<div id="statistical-transformations" class="section level3">
<h3>Statistical Transformations</h3>
<pre class="r"><code>ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>geom_bar draws a bar plot, here the x-axis displays the variable “cut” (from the diamonds dataset) and on the y-axis it displays count which is calculated by the bar chart.</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p>Note: algorithm to calculate new values for a graph is called stat – geom_bar() uses stat_count(). This shows that sometimes we can use geom_bar() and stat_count() interchangeably</p>
<pre class="r"><code>demo &lt;- tribble(
  ~cut,         ~freq,
  &quot;Fair&quot;,       1610,
  &quot;Good&quot;,       4906,
  &quot;Very Good&quot;,  12082,
  &quot;Premium&quot;,    13791,
  &quot;Ideal&quot;,      21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = &quot;identity&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>With this code we can override the default stat, from count to identity. Identity maps the height of the bars to the raw values of a y variable.</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = stat(prop), group = 1))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>y= stat(prop) allows us display a bar chart of proportion, instead of count.</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>the stat_summary() function summarises the y values for each unique x value</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>The (colour = cut) part code colors the outside of bars, as an outline.</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>The (fill = cut) part of the code fills the bars with color.</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>If we change the variable that we are mapping the fill aesthetic to, in this case “clarity” the bars become automatically stacked. Each colored rectangle represents a combination of cut and clarity.</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = &quot;fill&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<p>position = “fill” is useful because it makes each set of stacked bars the same height, making it easier to compare proportions across groups.</p>
<pre class="r"><code>ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = &quot;dodge&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>position = “dodge” places overlapping objects beside one another – easier to compare individual values.</p>
<pre class="r"><code>ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = &quot;jitter&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<p>Sometimes points overlap each other and it makes it hard to see where the mass of the data is. By setting (position = “jitter”) we can add a small amount of noise to each point and this spreads out the points.</p>
</div>
<div id="coordinate-systems" class="section level3">
<h3>Coordinate systems</h3>
<pre class="r"><code>ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>This is the original plot, the one that we have flipped is below.</p>
<pre class="r"><code>ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>coord_flip() switches the x and y axes. This gives us horizontal boxplots, and can help prevent labels from overlapping on x-axis.</p>
<pre class="r"><code>nz &lt;- map_data(&quot;nz&quot;)

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = &quot;white&quot;, colour = &quot;black&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-76-1.png" width="672" /></p>
<pre class="r"><code>ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = &quot;white&quot;, colour = &quot;black&quot;) +
  coord_quickmap()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-76-2.png" width="672" /></p>
<p>coord_quickmap() sets the correct aspect ratio for maps</p>
<pre class="r"><code>bar &lt;- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<pre class="r"><code>bar + coord_polar()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-77-2.png" width="672" /></p>
<p>We can also use coord_polar() which uses polar coordinates to reveal connections between a bar chart and a Coxcomb chart</p>
</div>
<div id="reading-28---graphics-for-communication" class="section level3">
<h3>Reading 28 - Graphics for Communication</h3>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  labs(
    title = &quot;Fuel efficiency generally decreases with engine size&quot;,
    subtitle = &quot;Two seaters (sports cars) are an exception because of their light weight&quot;,
    caption = &quot;Data from fueleconomy.gov&quot;
  )</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
<p>labs() allows us to add and change labels to our plot, title = "" adds a title to our plot, subtitle adds text in a smaller font under the title, caption adds text at the bottom right of the plot (often used to describe the source of the data)</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_smooth(se = FALSE) +
  labs(
    x = &quot;Engine displacement (L)&quot;,
    y = &quot;Highway fuel economy (mpg)&quot;,
    colour = &quot;Car type&quot;
  )</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p>here labs() serves to change the axis and legend titles. It helps understand more clearly what the axis represent.</p>
<pre class="r"><code>df &lt;- tibble(
  x = runif(10),
  y = runif(10)
)
ggplot(df, aes(x, y)) +
  geom_point() +
  labs(
    x = quote(sum(x[i] ^ 2, i == 1, n)),
    y = quote(alpha + beta + frac(delta, theta))
  )</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<p>When needed we can use mathematical equations instead of text.</p>
</div>
<div id="annotations" class="section level3">
<h3>Annotations</h3>
<pre class="r"><code>best_in_class &lt;- mpg %&gt;%
  group_by(class) %&gt;%
  filter(row_number(desc(hwy)) == 1)

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_text(aes(label = model), data = best_in_class)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>We can have labels inside the plot for specific observations. geom_text with the label aesthetic is what adds text to a point.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_label(aes(label = model), data = best_in_class, nudge_y = 2, alpha = 0.5)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>Here we changed geom_text to geom_label which draws a rectangle around the text, and nudge_y moves the labels slightly above the corresponding point (the greater nudge_y is the higher above the point the label will be). However, some of them still overlap. alpha = changes the transparency of our labels, if we increase ist (ex to 2) our labels won’t be transparent and we won’t be able to see any points etc behind them, the lower the alpha value the more transparent our labels are.</p>
<p>install.packages(“ggrepel”) — I had to install the package before being able to use for the first time.</p>
<pre class="r"><code>library(ggrepel)

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_point(size = 3, shape = 1, data = best_in_class) +
  ggrepel::geom_label_repel(aes(label = model), data = best_in_class)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>the ggrepel package automaticially adjusts the labels so that they don’t overlap. The third line of the code geom_point(size=3, shape=1, data = best_in_class) created a second layer of large hollow points (the black outline that we see around the labelled points).</p>
<pre class="r"><code>class_avg &lt;- mpg %&gt;%
  group_by(class) %&gt;%
  summarise(
    displ = median(displ),
    hwy = median(hwy)
  )</code></pre>
<p>summarise() ungrouping output (override with <code>.groups</code> argument)</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy, colour = class)) +
  ggrepel::geom_label_repel(aes(label = class),
                            data = class_avg,
                            size = 6,
                            label.size = 0,
                            segment.color = NA
  ) +
  geom_point() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-85-1.png" width="672" /></p>
<p>ggrrepel::geom_label_repel(aes(label=class)) etc. is what replaces the legend with labels on the plot, and theme(legend.position = "none) is what turns the legend off.</p>
<pre class="r"><code>label &lt;- mpg %&gt;%
  summarise(
    displ = max(displ),
    hwy = max(hwy),
    label = &quot;Increasing engine size is \nrelated to decreasing fuel economy.&quot;
  )</code></pre>
<p>The top part of the code allows us to create a single label, and here we are naming it. Using summarise() is also useful because we can compute the max of x and y to help us place the label in the corner.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_text(aes(label = label), data = label, vjust = &quot;top&quot;, hjust = &quot;right&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<p>This part of the code is where we write where we want the label to be placed. There are nine different combinations that we can use to control the alignment of the label, by changing hjust = and vjust= to ‘left’, ‘center’ and ‘right’.</p>
<pre class="r"><code>label &lt;- tibble(
  displ = Inf,
  hwy = Inf,
  label = &quot;Increasing engine size is \nrelated to decreasing fuel economy.&quot;
)</code></pre>
<p>By changing displ = max(displ) and hwy = max(hwy) to displ = Inf, and hwy = Inf the label will be placed exactly in the corner of the plot. also breaks up the line, and we can place it whereever we want within the text.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_text(aes(label = label), data = label, vjust = &quot;top&quot;, hjust = &quot;right&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<pre class="r"><code>&quot;Increasing engine size is related to decreasing fuel economy.&quot; %&gt;%
  stringr::str_wrap(width = 40) %&gt;%
  writeLines()</code></pre>
<pre><code>## Increasing engine size is related to
## decreasing fuel economy.</code></pre>
<p>Increasing engine size is related to decreasing fuel economy. This is another way to break up the lines, where (width=40) represented the number of characters we want per line.</p>
</div>
<div id="scales" class="section level3">
<h3>Scales</h3>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  scale_x_continuous() +
  scale_y_continuous() +
  scale_colour_discrete()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
<p>This is the default scale that ggplot2 uses but we can change the parameters according to our data.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  scale_y_continuous(breaks = seq(15, 40, by = 5))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>The last line of the code indicates that we want to adjust the scale of the y-axis, (breaks) lets us override the default scale. seq(15, 40, by =5) means that we want the y-axis to start at 15, end at 40 and increase in increments of 5.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(labels = NULL)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>Setting labels=NULL suppresses all of the labels.</p>
<pre class="r"><code>presidential %&gt;%
  mutate(id = 33 + row_number()) %&gt;%
  ggplot(aes(start, id)) +
  geom_point() +
  geom_segment(aes(xend = end, yend = id)) +
  scale_x_date(NULL, breaks = presidential$start, date_labels = &quot;&#39;%y&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
<p>Brakes can also be used to highlight where observations occur.</p>
</div>
<div id="changing-the-layout-of-the-legend" class="section level3">
<h3>Changing the layout of the legend</h3>
<pre class="r"><code>base &lt;- ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class))

base + theme(legend.position = &quot;left&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-95-1.png" width="672" /></p>
<p>base + theme(legend.position = “left”) base + theme(legend.position = “top”) base + theme(legend.position = “bottom”) base + theme(legend.position = “right”) # the default <em>Theme(legend.position = “left”) means that the legend will be on the left of the plot, but we can change “left” to top, bottom, or right.</em></p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = &quot;bottom&quot;) +
  guides(colour = guide_legend(nrow = 1, override.aes = list(size = 4)))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<p>The last line of the code indicates that we only want the legend to use 1 row (nrow = 1) and that the points in the legend should be larger than that in the plot (override.aes = list(size=4)) – which overrides the previous aesthetics.</p>
<pre class="r"><code>ggplot(diamonds, aes(carat, price)) +
  geom_bin2d()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<p>This is the original plot of the variables that we transformed below using log.</p>
<pre class="r"><code>ggplot(diamonds, aes(log10(carat), log10(price))) +
  geom_bin2d()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
<p>This is the transformed plot of the relationship between carat and price. Log transformation was perforomed on carat, shown by (log10(carat), and log was performed on price as shown by log10(price). This helps us see the relationship more clearly.</p>
<pre class="r"><code>ggplot(diamonds, aes(carat, price)) +
  geom_bin2d() + 
  scale_x_log10() + 
  scale_y_log10()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-99-1.png" width="672" /></p>
<p>This continues to be a plot of the log transformation but aes(carat, price) allows the axes to be labeled with their original names. But now with scale_x_log10 the scale of the x-axis is being transformed, and the same with the y-axis.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv)) +
  scale_colour_brewer(palette = &quot;Set1&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-100-1.png" width="672" /></p>
<p>We can choose the color palette we want to use in our plot - which is what the last line of the code does. The shades used are very different from one another.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv, shape = drv)) +
  scale_colour_brewer(palette = &quot;Set1&quot;)</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-101-1.png" width="672" /></p>
<p>The second line of the code (aes(color = drv, shape = drv)) means that every unique value is being a color and a shape.</p>
<pre class="r"><code>presidential %&gt;%
  mutate(id = 33 + row_number()) %&gt;%
  ggplot(aes(start, id, colour = party)) +
  geom_point() +
  geom_segment(aes(xend = end, yend = id)) +
  scale_colour_manual(values = c(Republican = &quot;red&quot;, Democratic = &quot;blue&quot;))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
<p>scale_color_manual allows us map specific colors and values. For example, here we can map “red” to Republican and “blue” to Democratic.</p>
<pre class="r"><code>df &lt;- tibble(
  x = rnorm(10000),
  y = rnorm(10000)
)
ggplot(df, aes(x, y)) +
  geom_hex() +
  coord_fixed()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-103-1.png" width="672" /></p>
<p>geom_hex() gives us a plot with hexagon points, and we get a plot with a color gradient.</p>
<p>install.packages(“viridis”) – installed the package viridis to be able to create the vignette.</p>
<pre class="r"><code>ggplot(df, aes(x, y)) +
  geom_hex() +
  viridis::scale_fill_viridis() +
  coord_fixed()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-104-1.png" width="672" /></p>
<p>By using the viridis package the vignette changes color, rather than being a gradient of a single color.</p>
</div>
<div id="zooming" class="section level3">
<h3>Zooming</h3>
<pre class="r"><code>ggplot(mpg, mapping = aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth() +
  coord_cartesian(xlim = c(5, 7), ylim = c(10, 30))</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>The last line of the code allows us to zoom into the plot. xlim = c(5,7) zooms into the points between the values of 5 and 7 on the x-axis. ylim = c(10,30) zooms into the points between 10 and 30 on the y-axis.</p>
<pre class="r"><code>mpg %&gt;%
  filter(displ &gt;= 5, displ &lt;= 7, hwy &gt;= 10, hwy &lt;= 30) %&gt;%
  ggplot(aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
<p>In this plot we have also changed the limits but the line isn’t as smooth as it could be and makes if difficult to interpret patterns.</p>
<pre class="r"><code>suv &lt;- mpg %&gt;% filter(class == &quot;suv&quot;)
compact &lt;- mpg %&gt;% filter(class == &quot;compact&quot;)

ggplot(suv, aes(displ, hwy, colour = drv)) +
  geom_point()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<pre class="r"><code>ggplot(compact, aes(displ, hwy, colour = drv)) +
  geom_point()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-107-2.png" width="672" /></p>
<p>Here we plotted two classes of cars separately and an issue with this is that it becomes difficult to compare the plots because they are all using different scales.</p>
<pre class="r"><code>x_scale &lt;- scale_x_continuous(limits = range(mpg$displ))
y_scale &lt;- scale_y_continuous(limits = range(mpg$hwy))
col_scale &lt;- scale_colour_discrete(limits = unique(mpg$drv))

ggplot(suv, aes(displ, hwy, colour = drv)) +
  geom_point() +
  x_scale +
  y_scale +
  col_scale</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-108-1.png" width="672" /></p>
<pre class="r"><code>ggplot(compact, aes(displ, hwy, colour = drv)) +
  geom_point() +
  x_scale +
  y_scale +
  col_scale</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-108-2.png" width="672" /></p>
<p>This creates scales that are shared by multiple plots, which means it will be easier to interpret the plots and compare them.</p>
<pre class="r"><code>ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_bw()</code></pre>
<p><img src="Journal_files/figure-html/unnamed-chunk-109-1.png" width="672" /></p>
<p>The last line of the code customizes the theme of our plot. We can change whether we want grid lines or not, along with the gray-scale of our plot.</p>
<pre class="r"><code>ggsave(&quot;my-plot.pdf&quot;)</code></pre>
<p>This simply saves our plot as a pdf to the disk drive.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
